apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: new-content-notifier
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: new-content-notifier
              image: gcr.io/exolutio/new-content-notifier
              env:
                - name: FIREBASE_WEB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: exolutio-firebase-secret-web-api-key
                      key: exolutio-firebase-secret-web-api-key
          restartPolicy: Never