name: exolutio
description: Show comments with citation inside LiveJournal articles.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.6.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_html: ^1.0.0
  get_it: ^4.0.2
  html: ^0.14.0+3
  http: ^0.12.1
  provider: ^4.1.3
  pull_to_refresh: ^1.6.0
  rxdart: ^0.24.1
  scroll_to_index: ^1.0.6
  shared_preferences: ^0.5.7+3
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  flutter_launcher_name: ^0.0.1
  mockito: ^4.1.1
  pedantic: ^1.9.0
  wakelock: ^0.1.4+1

flutter:
  uses-material-design: true
  fonts:
    - family: Merriweather_Sans
      fonts:
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Bold.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-BoldItalic.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-ExtraBold.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Italic.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Light.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-LightItalic.ttf
        - asset: assets/fonts/Merriweather_Sans/MerriweatherSans-Regular.ttf

flutter_launcher_name:
  name: "Exolutio"