name: evotexto
description: Show comments with citation inside LiveJournal articles.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_html: ^1.0.0
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  html: ^0.14.0+3
  http: ^0.12.1
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  throttling: ^0.8.0
  url_launcher: ^5.4.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  logging: ^0.11.4
  pedantic: ^1.9.0
  wakelock: ^0.1.4+1

flutter:
  uses-material-design: true