apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: new-content-notifier
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: pubsub-key
          containers:
            - name: new-content-notifier
              image: gcr.io/exolutio/new-content-notifier:latest
              volumeMounts:
                - name: google-cloud-key
                  mountPath: /var/secrets/google
              env:
                - name: FIREBASE_WEB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web-api-key
                      key: web-api-key
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/key.json
          restartPolicy: Never