apiVersion: batch/v1
kind: CronJob
metadata:
  name: new-content-notifier
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: google-cloud-key
              secret:
                secretName: pubsub-key
          containers:
            - name: new-content-notifier
              image: ivribalko/new-content-notifier:latest
              env:
                - name: FIREBASE_WEB_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: firebase
                      key: api-key
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  valueFrom:
                    secretKeyRef:
                      name: google
                      key: account
          restartPolicy: Never
