name: server
description: Send links from LiveJournal as push notifications.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.7.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  html: ^0.14.0+4
  http: ^0.12.2
  firebase_cloud_messaging_backend: ^1.0.1
  firedart: ^0.8.3
  shared:
    git:
      url: https://github.com/whitepyjamas/exolutio.git
      path: shared
